name: build
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt install p7zip python3-pip
          bash build/build.sh
      - uses: actions/upload-artifact@v4
        with:
          path: oneplus6_stock.7z
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oneplus6_stock.7z
          tag: 10.3.8
          overwrite: true
          body: 'archive built by `.github/workflows/build.yml`'
